[MeasureTop1CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=1
Substitute="":"---"

[MeasureTop2CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=2
Substitute="":"---"

[MeasureTop3CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=3
Substitute="":"---"

[MeasureTop4CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=4
Substitute="":"---"

[MeasureTop5CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=5
Substitute="":"---"