[MeterTopCPUTitle]
Meter=String
X=(#Scale#*5)
Y=(#Scale#*5)
FontSize=(#Scale#*13)
FontColor=#FontColor#
FontWeight=#FontWeight#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1
Text=TOP CPU 

[MeterTop1CPULabel]
Meter=String
MeasureName=MeasureTop1CPU
X=(#Scale#*5)
Y=(#Scale#*12)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop1CPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop1CPU:1] %
DynamicVariables=1

[MeterTop2CPULabel]
Meter=String
MeasureName=MeasureTop2CPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop2CPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop2CPU:1] %
DynamicVariables=1

[MeterTop3CPULabel]
Meter=String
MeasureName=MeasureTop3CPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop3CPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop3CPU:1] %
DynamicVariables=1

[MeterTop4CPULabel]
Meter=String
MeasureName=MeasureTop4CPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop4CPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop4CPU:1] %
DynamicVariables=1

[MeterTop5CPULabel]
Meter=String
MeasureName=MeasureTop5CPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop5CPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop5CPU:1] %
DynamicVariables=1