[MeterValueTopCPU0]
Meter=String
Text=[MeasureTop0CPU:1] %
MeterStyle=ValueStyle
Y=[0:Y]
[MeterValueTopCPU1]
Meter=String
Text=[MeasureTop1CPU:1] %
MeterStyle=ValueStyle
Y=[1:Y]
[MeterValueTopCPU2]
Meter=String
Text=[MeasureTop2CPU:1] %
MeterStyle=ValueStyle
Y=[2:Y]
[MeterValueTopCPU3]
Meter=String
Text=[MeasureTop3CPU:1] %
MeterStyle=ValueStyle
Y=[3:Y]
[MeterValueTopCPU4]
Meter=String
Text=[MeasureTop4CPU:1] %
MeterStyle=ValueStyle
Y=[4:Y]