[MeasureTop1GPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=1
Substitute="":"---"

[MeasureTop2GPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=2
Substitute="":"---"

[MeasureTop3GPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=3
Substitute="":"---"

[MeasureTop4GPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=4
Substitute="":"---"

[MeasureTop5GPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=5
Substitute="":"---"