[MeterTopGPUTitle]
Meter=String
X=(#Scale#*5)
Y=(#Scale#*5)
FontSize=(#Scale#*13)
FontColor=#FontColor#
FontWeight=#FontWeight#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1
Text=TOP GPU 

[MeterTop1GPULabel]
Meter=String
MeasureName=MeasureTop1GPU
X=(#Scale#*5)
Y=(#Scale#*12)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop1GPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop1GPU:1] %
DynamicVariables=1

[MeterTop2GPULabel]
Meter=String
MeasureName=MeasureTop2GPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop2GPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop2GPU:1] %
DynamicVariables=1

[MeterTop3GPULabel]
Meter=String
MeasureName=MeasureTop3GPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop3GPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop3GPU:1] %
DynamicVariables=1

[MeterTop4GPULabel]
Meter=String
MeasureName=MeasureTop4GPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop4GPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop4GPU:1] %
DynamicVariables=1

[MeterTop5GPULabel]
Meter=String
MeasureName=MeasureTop5GPU
X=(#Scale#*5)
Y=(#Scale#*5)R
W=(#Scale#*140)
Clipstring=1
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=left
AntiAlias=1

[MeterTop5GPUValue]
Meter=String
X=(#Scale#*250)
Y=0r
FontSize=(#Scale#*13)
FontColor=#FontColor#
StringStyle=normal
FontFace=#Font1#
StringAlign=right
AntiAlias=1
Text=[MeasureTop5GPU:1] %
DynamicVariables=1