[MeterValueTopGPU0]
Meter=String
Text=[MeasureTop0GPU:1] %
MeterStyle=ValueStyle
Y=[0:Y]
[MeterValueTopGPU1]
Meter=String
Text=[MeasureTop1GPU:1] %
MeterStyle=ValueStyle
Y=[1:Y]
[MeterValueTopGPU2]
Meter=String
Text=[MeasureTop2GPU:1] %
MeterStyle=ValueStyle
Y=[2:Y]
[MeterValueTopGPU3]
Meter=String
Text=[MeasureTop3GPU:1] %
MeterStyle=ValueStyle
Y=[3:Y]
[MeterValueTopGPU4]
Meter=String
Text=[MeasureTop4GPU:1] %
MeterStyle=ValueStyle
Y=[4:Y]