[Variables]
__CenterHorizontal=Center horizontally
__CenterVertical=Center vertically
__EditVariables=Edit variables
__SkinMenu=Open skin menu...
__RefreshGroup=Refresh Robux

; ██     ██ ███████  █████  ████████ ██   ██ ███████ ██████  
; ██     ██ ██      ██   ██    ██    ██   ██ ██      ██   ██ 
; ██  █  ██ █████   ███████    ██    ███████ █████   ██████  
; ██ ███ ██ ██      ██   ██    ██    ██   ██ ██      ██   ██ 
;  ███ ███  ███████ ██   ██    ██    ██   ██ ███████ ██   ██ 

__Loading=Loading...

; Alerts ToolTip labels
AlertsTipTitle=Weather Alerts!
AlertsTipText=Click to check weather.com

; Context Menu labels
ObservedAt=Observed at
ChooseLocation=Choose Location
EditWeatherVariables=Edit Weather Variables
EditTranslationVariables=Edit Translation Variables
EditGeneralVariables=Edit General Variables
Open@ResourcesFolder=Open @Resources Folder
MoreActions=More actions ...

; Skin labels
FeelsLike=Feels Like
Humidity=Humidity
DewPoint=DewPoint
Wind=Wind
Pressure=Pressure
Change=Change
Sunrise=Sunrise
Sunset=Sunset
High=High
Low=Low

; Skin value-string translations
Calm=Calm
Falling=Falling
Steady=Steady
Rising=Rising
