[MeasureTop1RAM]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=1
Substitute="":"---"

[MeasureTop1RAMCalc]
Measure=Calc
Formula=MeasureTop1RAM

[MeasureTop2RAM]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=2
Substitute="":"---"

[MeasureTop2RAMCalc]
Measure=Calc
Formula=MeasureTop2RAM

[MeasureTop3RAM]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=3
Substitute="":"---"

[MeasureTop3RAMCalc]
Measure=Calc
Formula=MeasureTop3RAM

[MeasureTop4RAM]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=4
Substitute="":"---"

[MeasureTop4RAMCalc]
Measure=Calc
Formula=MeasureTop4RAM

[MeasureTop5RAM]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=5
Substitute="":"---"

[MeasureTop5RAMCalc]
Measure=Calc
Formula=MeasureTop5RAM