[MeterValueTopRAM0]
Meter=String
MeasureName=MeasureTop0RAMCalc
MeterStyle=ValueStyle | RamStyle
Y=[0:Y]
[MeterValueTopRAM1]
Meter=String
MeasureName=MeasureTop1RAMCalc
MeterStyle=ValueStyle | RamStyle
Y=[1:Y]
[MeterValueTopRAM2]
Meter=String
MeasureName=MeasureTop2RAMCalc
MeterStyle=ValueStyle | RamStyle
Y=[2:Y]
[MeterValueTopRAM3]
Meter=String
MeasureName=MeasureTop3RAMCalc
MeterStyle=ValueStyle | RamStyle
Y=[3:Y]
[MeterValueTopRAM4]
Meter=String
MeasureName=MeasureTop4RAMCalc
MeterStyle=ValueStyle | RamStyle
Y=[4:Y]