[MeasureBand0]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=0
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak0]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=0
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand0]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand0

[MeterPeak0]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak0
[MeasureBand1]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak1]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand1]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand1

[MeterPeak1]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak1
[MeasureBand2]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak2]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand2]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand2

[MeterPeak2]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak2
[MeasureBand3]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak3]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand3]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand3

[MeterPeak3]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak3
[MeasureBand4]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak4]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand4]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand4

[MeterPeak4]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak4
[MeasureBand5]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak5]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand5]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand5

[MeterPeak5]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak5
[MeasureBand6]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak6]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand6]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand6

[MeterPeak6]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak6
[MeasureBand7]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak7]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand7]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand7

[MeterPeak7]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak7
[MeasureBand8]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak8]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand8]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand8

[MeterPeak8]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak8
[MeasureBand9]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak9]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand9]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand9

[MeterPeak9]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak9
[MeasureBand10]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak10]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand10]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand10

[MeterPeak10]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak10
[MeasureBand11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand11]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand11

[MeterPeak11]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak11
[MeasureBand12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand12]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand12

[MeterPeak12]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak12
[MeasureBand13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand13]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand13

[MeterPeak13]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak13
[MeasureBand14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand14]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand14

[MeterPeak14]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak14
[MeasureBand15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand15]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand15

[MeterPeak15]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak15
[MeasureBand16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand16]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand16

[MeterPeak16]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak16
[MeasureBand17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand17]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand17

[MeterPeak17]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak17
[MeasureBand18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand18]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand18

[MeterPeak18]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak18
[MeasureBand19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand19]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand19

[MeterPeak19]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak19
[MeasureBand20]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak20]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand20]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand20

[MeterPeak20]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak20
[MeasureBand21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand21]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand21

[MeterPeak21]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak21
[MeasureBand22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand22]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand22

[MeterPeak22]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak22
[MeasureBand23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand23]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand23

[MeterPeak23]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak23
[MeasureBand24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=24
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=24
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand24]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand24

[MeterPeak24]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak24
[MeasureBand25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=25
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=25
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand25]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand25

[MeterPeak25]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak25
[MeasureBand26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=26
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=26
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand26]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand26

[MeterPeak26]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak26
[MeasureBand27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=27
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=27
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand27]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand27

[MeterPeak27]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak27
[MeasureBand28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=28
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=28
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand28]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand28

[MeterPeak28]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak28
[MeasureBand29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=29
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=29
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand29]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand29

[MeterPeak29]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak29
[MeasureBand30]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=30
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak30]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=30
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand30]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand30

[MeterPeak30]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak30
[MeasureBand31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=31
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=31
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand31]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand31

[MeterPeak31]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak31
[MeasureBand32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=32
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=32
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand32]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand32

[MeterPeak32]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak32
[MeasureBand33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=33
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=33
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand33]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand33

[MeterPeak33]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak33
[MeasureBand34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=34
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=34
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand34]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand34

[MeterPeak34]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak34
[MeasureBand35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=35
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=35
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand35]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand35

[MeterPeak35]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak35
[MeasureBand36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=36
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=36
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand36]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand36

[MeterPeak36]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak36
[MeasureBand37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=37
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=37
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand37]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand37

[MeterPeak37]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak37
[MeasureBand38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=38
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=38
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand38]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand38

[MeterPeak38]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak38
[MeasureBand39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=39
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=39
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand39]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand39

[MeterPeak39]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak39
[MeasureBand40]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=40
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak40]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=40
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand40]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand40

[MeterPeak40]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak40
[MeasureBand41]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=41
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak41]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=41
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand41]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand41

[MeterPeak41]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak41
[MeasureBand42]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=42
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak42]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=42
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand42]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand42

[MeterPeak42]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak42
[MeasureBand43]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=43
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak43]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=43
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand43]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand43

[MeterPeak43]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak43
[MeasureBand44]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=44
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak44]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=44
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand44]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand44

[MeterPeak44]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak44
[MeasureBand45]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=45
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak45]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=45
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand45]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand45

[MeterPeak45]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak45
[MeasureBand46]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=46
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak46]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=46
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand46]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand46

[MeterPeak46]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak46
[MeasureBand47]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=47
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak47]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=47
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand47]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand47

[MeterPeak47]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak47
[MeasureBand48]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=48
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak48]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=48
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand48]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand48

[MeterPeak48]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak48
[MeasureBand49]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=49
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak49]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=49
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand49]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand49

[MeterPeak49]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak49
[MeasureBand50]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=50
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak50]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=50
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand50]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand50

[MeterPeak50]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak50
[MeasureBand51]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=51
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak51]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=51
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand51]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand51

[MeterPeak51]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak51
[MeasureBand52]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=52
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak52]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=52
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand52]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand52

[MeterPeak52]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak52
[MeasureBand53]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=53
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak53]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=53
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand53]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand53

[MeterPeak53]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak53
[MeasureBand54]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=54
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak54]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=54
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand54]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand54

[MeterPeak54]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak54
[MeasureBand55]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=55
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak55]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=55
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand55]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand55

[MeterPeak55]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak55
[MeasureBand56]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=56
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak56]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=56
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand56]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand56

[MeterPeak56]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak56
[MeasureBand57]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=57
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak57]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=57
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand57]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand57

[MeterPeak57]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak57
[MeasureBand58]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=58
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak58]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=58
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand58]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand58

[MeterPeak58]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak58
[MeasureBand59]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=59
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak59]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=59
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand59]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand59

[MeterPeak59]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak59
[MeasureBand60]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=60
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak60]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=60
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand60]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand60

[MeterPeak60]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak60
[MeasureBand61]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=61
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak61]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=61
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand61]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand61

[MeterPeak61]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak61
[MeasureBand62]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=62
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak62]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=62
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand62]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand62

[MeterPeak62]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak62
[MeasureBand63]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=63
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak63]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=63
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand63]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand63

[MeterPeak63]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak63
[MeasureBand64]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=64
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak64]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=64
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand64]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand64

[MeterPeak64]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak64
[MeasureBand65]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=65
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak65]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=65
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand65]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand65

[MeterPeak65]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak65
[MeasureBand66]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=66
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak66]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=66
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand66]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand66

[MeterPeak66]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak66
[MeasureBand67]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=67
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak67]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=67
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand67]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand67

[MeterPeak67]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak67
[MeasureBand68]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=68
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak68]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=68
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand68]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand68

[MeterPeak68]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak68
[MeasureBand69]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=69
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak69]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=69
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand69]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand69

[MeterPeak69]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak69
[MeasureBand70]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=70
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak70]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=70
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand70]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand70

[MeterPeak70]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak70
[MeasureBand71]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=71
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak71]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=71
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand71]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand71

[MeterPeak71]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak71
[MeasureBand72]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=72
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak72]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=72
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand72]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand72

[MeterPeak72]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak72
[MeasureBand73]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=73
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak73]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=73
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand73]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand73

[MeterPeak73]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak73
[MeasureBand74]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=74
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak74]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=74
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand74]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand74

[MeterPeak74]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak74
[MeasureBand75]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=75
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak75]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=75
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand75]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand75

[MeterPeak75]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak75
[MeasureBand76]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=76
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak76]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=76
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand76]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand76

[MeterPeak76]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak76
[MeasureBand77]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=77
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak77]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=77
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand77]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand77

[MeterPeak77]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak77
[MeasureBand78]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=78
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak78]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=78
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand78]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand78

[MeterPeak78]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak78
[MeasureBand79]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=79
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak79]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=79
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand79]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand79

[MeterPeak79]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak79
[MeasureBand80]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=80
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak80]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=80
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand80]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand80

[MeterPeak80]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak80
[MeasureBand81]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=81
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak81]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=81
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand81]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand81

[MeterPeak81]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak81
[MeasureBand82]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=82
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak82]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=82
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand82]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand82

[MeterPeak82]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak82
[MeasureBand83]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=83
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak83]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=83
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand83]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand83

[MeterPeak83]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak83
[MeasureBand84]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=84
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak84]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=84
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand84]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand84

[MeterPeak84]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak84
[MeasureBand85]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=85
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak85]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=85
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand85]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand85

[MeterPeak85]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak85
[MeasureBand86]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=86
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak86]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=86
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand86]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand86

[MeterPeak86]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak86
[MeasureBand87]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=87
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak87]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=87
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand87]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand87

[MeterPeak87]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak87
[MeasureBand88]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=88
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak88]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=88
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand88]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand88

[MeterPeak88]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak88
[MeasureBand89]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=89
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak89]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=89
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand89]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand89

[MeterPeak89]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak89
[MeasureBand90]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=90
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak90]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=90
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand90]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand90

[MeterPeak90]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak90
[MeasureBand91]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=91
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak91]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=91
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand91]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand91

[MeterPeak91]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak91
[MeasureBand92]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=92
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak92]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=92
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand92]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand92

[MeterPeak92]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak92
[MeasureBand93]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=93
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak93]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=93
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand93]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand93

[MeterPeak93]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak93
[MeasureBand94]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=94
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak94]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=94
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand94]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand94

[MeterPeak94]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak94
[MeasureBand95]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=95
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak95]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=95
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand95]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand95

[MeterPeak95]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak95
[MeasureBand96]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=96
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak96]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=96
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand96]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand96

[MeterPeak96]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak96
[MeasureBand97]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=97
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak97]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=97
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand97]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand97

[MeterPeak97]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak97
[MeasureBand98]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=98
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak98]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=98
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand98]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand98

[MeterPeak98]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak98
[MeasureBand99]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=99
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak99]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=99
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand99]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand99

[MeterPeak99]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak99
[MeasureBand100]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=100
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak100]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=100
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand100]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand100

[MeterPeak100]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak100
[MeasureBand101]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=101
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak101]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=101
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand101]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand101

[MeterPeak101]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak101
[MeasureBand102]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=102
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak102]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=102
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand102]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand102

[MeterPeak102]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak102
[MeasureBand103]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=103
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak103]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=103
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand103]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand103

[MeterPeak103]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak103
[MeasureBand104]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=104
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak104]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=104
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand104]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand104

[MeterPeak104]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak104
[MeasureBand105]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=105
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak105]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=105
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand105]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand105

[MeterPeak105]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak105
[MeasureBand106]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=106
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak106]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=106
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand106]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand106

[MeterPeak106]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak106
[MeasureBand107]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=107
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak107]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=107
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand107]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand107

[MeterPeak107]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak107
[MeasureBand108]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=108
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak108]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=108
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand108]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand108

[MeterPeak108]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak108
[MeasureBand109]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=109
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak109]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=109
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand109]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand109

[MeterPeak109]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak109
[MeasureBand110]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=110
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak110]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=110
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand110]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand110

[MeterPeak110]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak110
[MeasureBand111]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=111
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak111]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=111
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand111]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand111

[MeterPeak111]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak111
[MeasureBand112]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=112
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak112]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=112
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand112]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand112

[MeterPeak112]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak112
[MeasureBand113]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=113
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak113]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=113
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand113]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand113

[MeterPeak113]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak113
[MeasureBand114]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=114
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak114]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=114
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand114]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand114

[MeterPeak114]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak114
[MeasureBand115]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=115
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak115]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=115
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand115]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand115

[MeterPeak115]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak115
[MeasureBand116]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=116
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak116]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=116
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand116]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand116

[MeterPeak116]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak116
[MeasureBand117]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=117
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak117]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=117
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand117]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand117

[MeterPeak117]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak117
[MeasureBand118]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=118
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak118]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=118
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand118]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand118

[MeterPeak118]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak118
[MeasureBand119]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=119
Channel=Auto
HandlerName=MainFinalOutput

[MeasurePeak119]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudioAnalyzer
Type=Child
Index=119
Channel=Auto
HandlerName=PeakFinalOutput

[MeterBand119]
Meter=Bar
MeterStyle=BandStyle
MeasureName=MeasureBand119

[MeterPeak119]
Meter=Bar
MeterStyle=PeakStyle
MeasureName=MeasurePeak119

